/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import javax.swing.JFrame;

/**
 *
 * @author irvin
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        LBLLOGO = new javax.swing.JLabel();
        btnPasajero = new javax.swing.JButton();
        btnRegReserva = new javax.swing.JButton();
        btnRegVuelos = new javax.swing.JButton();
        btnRegAeropuerto = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        LBLTITULO1 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        btnMinimizar = new javax.swing.JButton();
        btnMaximizar = new javax.swing.JButton();
        pnlContenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(133, 190, 207));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LBLLOGO.setFont(new java.awt.Font("Race Sport", 0, 36)); // NOI18N
        LBLLOGO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLLOGO.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(LBLLOGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 160, 140));

        btnPasajero.setFont(new java.awt.Font("Racer", 0, 14)); // NOI18N
        btnPasajero.setText("REGISTRO PASAJERO");
        btnPasajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasajeroActionPerformed(evt);
            }
        });
        jPanel2.add(btnPasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 198, 50));

        btnRegReserva.setFont(new java.awt.Font("Racer", 0, 14)); // NOI18N
        btnRegReserva.setText("REGISTRO RESERVA");
        btnRegReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegReservaActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 198, 50));

        btnRegVuelos.setFont(new java.awt.Font("Racer", 0, 14)); // NOI18N
        btnRegVuelos.setText("REGISTRAR VUELOS");
        btnRegVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegVuelosActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegVuelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 198, 50));

        btnRegAeropuerto.setFont(new java.awt.Font("Racer", 0, 14)); // NOI18N
        btnRegAeropuerto.setText("REGISTRO AEROPUERTO");
        btnRegAeropuerto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnRegAeropuerto.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnRegAeropuerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegAeropuertoActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegAeropuerto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 198, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -7, 220, 650));

        jPanel1.setBackground(new java.awt.Color(133, 190, 207));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LBLTITULO1.setFont(new java.awt.Font("Race Sport", 0, 50)); // NOI18N
        LBLTITULO1.setForeground(new java.awt.Color(255, 255, 255));
        LBLTITULO1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLTITULO1.setText("SISTEMA DE VUELO");
        LBLTITULO1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(LBLTITULO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 720, 90));

        btnCerrar.setBackground(new java.awt.Color(133, 190, 207));
        btnCerrar.setForeground(new java.awt.Color(249, 248, 220));
        btnCerrar.setBorder(null);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 28, 40, 40));

        btnMinimizar.setBackground(new java.awt.Color(133, 190, 207));
        btnMinimizar.setForeground(new java.awt.Color(249, 248, 220));
        btnMinimizar.setBorder(null);
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 28, 40, 40));

        btnMaximizar.setBackground(new java.awt.Color(133, 190, 207));
        btnMaximizar.setForeground(new java.awt.Color(249, 248, 220));
        btnMaximizar.setBorder(null);
        btnMaximizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaximizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnMaximizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(654, 28, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 800, 90));

        javax.swing.GroupLayout pnlContenedorLayout = new javax.swing.GroupLayout(pnlContenedor);
        pnlContenedor.setLayout(pnlContenedorLayout);
        pnlContenedorLayout.setHorizontalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        pnlContenedorLayout.setVerticalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        getContentPane().add(pnlContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasajeroActionPerformed
        JPLPasajeros pas= new JPLPasajeros();
        pas.setSize(750, 550);
        pas.setLocation(0,0);
        pnlContenedor.removeAll();
        pnlContenedor.add(pas);
        pnlContenedor.revalidate();
        pnlContenedor.repaint();

    }//GEN-LAST:event_btnPasajeroActionPerformed

    private void btnRegReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegReservaActionPerformed
        JPLReservas res= new JPLReservas();
        res.setSize(750, 550);
        res.setLocation(0,0);
        pnlContenedor.removeAll();
        pnlContenedor.add(res);
        pnlContenedor.revalidate();
        pnlContenedor.repaint();
    }//GEN-LAST:event_btnRegReservaActionPerformed

    private void btnRegVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegVuelosActionPerformed
        JPLVuelos vue= new JPLVuelos();
        vue.setSize(750, 550);
        vue.setLocation(0,0);
        pnlContenedor.removeAll();
        pnlContenedor.add(vue);
        pnlContenedor.revalidate();
        pnlContenedor.repaint();

    }//GEN-LAST:event_btnRegVuelosActionPerformed

    private void btnRegAeropuertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegAeropuertoActionPerformed
        JPLAeropuertos aero= new JPLAeropuertos();
        aero.setSize(750, 550);
        aero.setLocation(0,0);
        pnlContenedor.removeAll();
        pnlContenedor.add(aero);
        pnlContenedor.revalidate();
        pnlContenedor.repaint();

    }//GEN-LAST:event_btnRegAeropuertoActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizarActionPerformed

    private void btnMaximizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaximizarActionPerformed
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_btnMaximizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBLLOGO;
    private javax.swing.JLabel LBLTITULO1;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnMaximizar;
    private javax.swing.JButton btnMinimizar;
    private javax.swing.JButton btnPasajero;
    private javax.swing.JButton btnRegAeropuerto;
    private javax.swing.JButton btnRegReserva;
    private javax.swing.JButton btnRegVuelos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnlContenedor;
    // End of variables declaration//GEN-END:variables
}
