/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import Datos.Conexion;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import  java.sql.ResultSet;
import net.proteanit.sql.DbUtils;
import Datos.Pasajeros;
/**
 *
 * @author irvin
 */
public class JPLPasajeros extends javax.swing.JPanel {

    /**
     * Creates new form JPLPasajeros
     */
    public JPLPasajeros() {
        initComponents();
    }
            private void limpiar()
    {
        txtIDPasajero.setText("");
        txtNumeroDoc.setText("");
        txtNomCompleto.setText("");
        txtTelefono.setText("");
        jdcFechaNacimiento.setDate(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnCosultar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tlbPasajeros = new javax.swing.JTable();
        lblNumeroDoc = new javax.swing.JLabel();
        lblNombreCompleto = new javax.swing.JLabel();
        lblFechaNacimiento = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblIDPasajero = new javax.swing.JLabel();
        txtIDPasajero = new javax.swing.JTextField();
        txtNumeroDoc = new javax.swing.JTextField();
        txtNomCompleto = new javax.swing.JTextField();
        jdcFechaNacimiento = new com.toedter.calendar.JDateChooser();
        txtTelefono = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscar.setFont(new java.awt.Font("Racer", 0, 14)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 110, 27));

        btnNuevo.setFont(new java.awt.Font("Racer", 0, 14)); // NOI18N
        btnNuevo.setText("NUEVO");
        btnNuevo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 110, 27));

        btnCosultar.setFont(new java.awt.Font("Racer", 0, 14)); // NOI18N
        btnCosultar.setText("CONSULTAR");
        btnCosultar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCosultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCosultarActionPerformed(evt);
            }
        });
        add(btnCosultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 110, 27));

        btnGuardar.setFont(new java.awt.Font("Racer", 0, 14)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 110, 27));

        btnBorrar.setFont(new java.awt.Font("Racer", 0, 14)); // NOI18N
        btnBorrar.setText("BORRAR");
        btnBorrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 110, 27));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setFont(new java.awt.Font("Hauser", 0, 12)); // NOI18N

        tlbPasajeros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tlbPasajeros);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 710, 140));

        lblNumeroDoc.setFont(new java.awt.Font("Racer", 0, 18)); // NOI18N
        lblNumeroDoc.setText("NUMERO DOCUMENTO");
        add(lblNumeroDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, 30));

        lblNombreCompleto.setFont(new java.awt.Font("Racer", 0, 18)); // NOI18N
        lblNombreCompleto.setText("NOMBRE COMPLETO");
        add(lblNombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, 30));

        lblFechaNacimiento.setFont(new java.awt.Font("Racer", 0, 18)); // NOI18N
        lblFechaNacimiento.setText("FECHA NACIMIENTO");
        add(lblFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, 30));

        lblTelefono.setFont(new java.awt.Font("Racer", 0, 18)); // NOI18N
        lblTelefono.setText("TELEFONO");
        add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, 30));

        lblIDPasajero.setFont(new java.awt.Font("Racer", 0, 18)); // NOI18N
        lblIDPasajero.setText("IDENTIFICADOR PASAJERO");
        add(lblIDPasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, 30));

        txtIDPasajero.setFont(new java.awt.Font("Stainless Black", 0, 12)); // NOI18N
        add(txtIDPasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 82, 120, 30));

        txtNumeroDoc.setFont(new java.awt.Font("Stainless Black", 0, 12)); // NOI18N
        add(txtNumeroDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 142, 120, 30));

        txtNomCompleto.setFont(new java.awt.Font("Stainless Black", 0, 12)); // NOI18N
        add(txtNomCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 192, 120, 30));

        jdcFechaNacimiento.setFont(new java.awt.Font("Stainless Black", 0, 12)); // NOI18N
        add(jdcFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 252, 130, 30));

        txtTelefono.setFont(new java.awt.Font("Stainless Black", 0, 12)); // NOI18N
        add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 312, 120, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        String ID = "";
        if (  ID.equals(txtIDPasajero.getText() ) ){
            JOptionPane.showMessageDialog(null,
                "Debe digitar algo en el campo de Identificador",
                "Mensaje Importante",
                JOptionPane.ERROR_MESSAGE);
        } else{
            try{
                Pasajeros miPasajero = Conexion.obtenerPasajero(txtIDPasajero.getText() );
                txtNumeroDoc.setText(miPasajero.getNumeroDocumento());
                txtNomCompleto.setText(miPasajero.getNombreCompleto());
                jdcFechaNacimiento.setDate(new java.util.Date(miPasajero.getFechaNacimiento().getTime()));
                txtTelefono.setText(miPasajero.getTelefono());
            }catch (SQLException ex){
                Logger.getLogger(JPLPasajeros.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        try {
            int siguiente = Conexion.siguientePasajero();
            txtIDPasajero.setText(String.valueOf(siguiente) );
        } catch (SQLException ex) {
            Logger.getLogger(JPLPasajeros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnCosultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCosultarActionPerformed
        ResultSet resultad;
        try {
            resultad = Conexion.listarPasajero();
            tlbPasajeros.setModel(DbUtils.resultSetToTableModel(resultad));
        } catch (SQLException ex) {
            Logger.getLogger(JPLPasajeros.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_btnCosultarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        //-- Guardar asume guardar nuevo y modificar

        //-- Creamos una copia del objeto y le llenamos los datos con el formulario
        Pasajeros miPasajero = new Pasajeros();
        miPasajero.setPasajeroID(Integer.parseInt(txtIDPasajero.getText()));
        miPasajero.setNumeroDocumento(txtNumeroDoc.getText());
        miPasajero.setNombreCompleto(txtNomCompleto.getText());
        miPasajero.setFechaNacimiento(new java.sql.Date(jdcFechaNacimiento.getDate().getTime()));
        miPasajero.setTelefono(txtTelefono.getText());
        int indice = 0;

        try {
            Pasajeros Consultada = Conexion.obtenerPasajero(txtIDPasajero.getText() );
            if (Consultada != null){
                indice = Consultada.getPasajeroID();
            }
            else {
                indice = 0;
            }
        } catch (SQLException ex) {
            indice = 0;
        }

        //---Insertar o Modificar en la tabla
        if (indice == 0){
            try {

                if (Conexion.insetPasajero(miPasajero) != 0) {
                    JOptionPane.showMessageDialog(null, "Pasajero Guardado" );
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.toString() );
            }
        }else{
            try {
                if (Conexion.updatePasajero(miPasajero) != 0) {
                    JOptionPane.showMessageDialog(null, "Pasajero Modificado" );
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.toString() );
            }

        }
        btnCosultar.doClick();
        limpiar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        String ID = "";
        if (  ID.equals(txtIDPasajero.getText() ) ){
            JOptionPane.showMessageDialog(null,
                "Debe digitar algo en el campo de Identificador",
                "Mensaje Importante",
                JOptionPane.ERROR_MESSAGE);
        } else{
            try{
                if (Conexion.borrarPasajero(Integer.parseInt(txtIDPasajero.getText())) != 0) {
                    JOptionPane.showMessageDialog(null, "Pasajero Borrado" );
                }
            }catch (SQLException ex) {
                Logger.getLogger(JPLPasajeros.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        btnCosultar.doClick();
        limpiar();
    }//GEN-LAST:event_btnBorrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCosultar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcFechaNacimiento;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblIDPasajero;
    private javax.swing.JLabel lblNombreCompleto;
    private javax.swing.JLabel lblNumeroDoc;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTable tlbPasajeros;
    private javax.swing.JTextField txtIDPasajero;
    private javax.swing.JTextField txtNomCompleto;
    private javax.swing.JTextField txtNumeroDoc;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
