/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

/**
 *
 * @author irvin
 */
public class JPLPasajeros extends javax.swing.JPanel {

    /**
     * Creates new form JPLPasajeros
     */
    public JPLPasajeros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnCosultar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tlbPasajeros = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscar.setFont(new java.awt.Font("Racer", 0, 14)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 110, 27));

        btnNuevo.setFont(new java.awt.Font("Racer", 0, 14)); // NOI18N
        btnNuevo.setText("NUEVO");
        btnNuevo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 110, 27));

        btnCosultar.setFont(new java.awt.Font("Racer", 0, 14)); // NOI18N
        btnCosultar.setText("CONSULTAR");
        btnCosultar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCosultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCosultarActionPerformed(evt);
            }
        });
        add(btnCosultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 110, 27));

        btnGuardar.setFont(new java.awt.Font("Racer", 0, 14)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 110, 27));

        btnBorrar.setFont(new java.awt.Font("Racer", 0, 14)); // NOI18N
        btnBorrar.setText("BORRAR");
        btnBorrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 110, 27));

        tlbPasajeros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tlbPasajeros);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 610, 140));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        String ID = "";
        if (  ID.equals(txtIDAeropuerto.getText() ) ){
            JOptionPane.showMessageDialog(null,
                "Debe digitar algo en el campo de Identificador",
                "Mensaje Importante",
                JOptionPane.ERROR_MESSAGE);
        } else{
            try{
                Aeropuertos miAeropuerto = Conexion.obtenerAeropuerto(txtIDAeropuerto.getText() );
                txtCodigoIATA.setText(miAeropuerto.getCodigoIATA());
                txtNomAeropuerto.setText(miAeropuerto.getNombreAeropuerto());
                txtCiudad.setText(miAeropuerto.getCodigoIATA());
                txtPais.setText(miAeropuerto.getPais());
            }catch (SQLException ex){
                Logger.getLogger(JPLAeropuertos.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        try {
            int siguiente = Conexion.siguienteAeropuerto();
            txtIDAeropuerto.setText(String.valueOf(siguiente) );
        } catch (SQLException ex) {
            Logger.getLogger(JPLAeropuertos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnCosultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCosultarActionPerformed
        ResultSet resultad;
        try {
            resultad = Conexion.listarAeropuerto();
            tlbPasajeros.setModel(DbUtils.resultSetToTableModel(resultad));
        } catch (SQLException ex) {
            Logger.getLogger(JPLAeropuertos.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_btnCosultarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        //-- Guardar asume guardar nuevo y modificar

        //-- Creamos una copia del objeto y le llenamos los datos con el formulario
        Aeropuertos miAeropuerto = new Aeropuertos();
        miAeropuerto.setAeropuertoID(Integer.parseInt(txtIDAeropuerto.getText()));
        miAeropuerto.setCodigoIATA(txtCodigoIATA.getText());
        miAeropuerto.setNombreAeropuerto(txtNomAeropuerto.getText());
        miAeropuerto.setCiudad(txtCiudad.getText());
        miAeropuerto.setPais(txtPais.getText());
        int indice = 0;

        try {
            Aeropuertos Consultada = Conexion.obtenerAeropuerto(txtIDAeropuerto.getText() );
            if (Consultada != null){
                indice = Consultada.getAeropuertoID();
            }
            else {
                indice = 0;
            }
        } catch (SQLException ex) {
            indice = 0;
        }

        //---Insertar o Modificar en la tabla
        if (indice == 0){
            try {

                if (Conexion.insertAeropuerto(miAeropuerto) != 0) {
                    JOptionPane.showMessageDialog(null, "Aeropuerto Guardado" );
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.toString() );
            }
        }else{
            try {
                if (Conexion.updateAeropuerto(miAeropuerto) != 0) {
                    JOptionPane.showMessageDialog(null, "Aeropuerto Modificado" );
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.toString() );
            }

        }
        btnCosultar.doClick();
        limpiar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        String ID = "";
        if (  ID.equals(txtIDAeropuerto.getText() ) ){
            JOptionPane.showMessageDialog(null,
                "Debe digitar algo en el campo de Identificador",
                "Mensaje Importante",
                JOptionPane.ERROR_MESSAGE);
        } else{
            try{
                if (Conexion.borrarAeropuerto(Integer.parseInt(txtIDAeropuerto.getText())) != 0) {
                    JOptionPane.showMessageDialog(null, "Aeropuerto Borrado" );
                }
            }catch (SQLException ex) {
                Logger.getLogger(JPLAeropuertos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        btnCosultar.doClick();
        limpiar();
    }//GEN-LAST:event_btnBorrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCosultar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tlbPasajeros;
    // End of variables declaration//GEN-END:variables
}
