/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import Datos.Conexion;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import  java.sql.ResultSet;
import net.proteanit.sql.DbUtils;
import Datos.Pasajeros;
import Datos.Reservas;
import Datos.Vuelos;
/**
 *
 * @author irvin
 */
public class JPLReservas extends javax.swing.JPanel {

    /**
     * Creates new form JPLReservas
     */
    public JPLReservas() {
        initComponents();
    }
    private void limpiar()
    {
        txtIDReserva.setText("");
        txtFkPasajero.setText("");
        txtFKVuelo.setText("");
        txtPrecioFinal.setText("");
        jdcFechaReserva.setDate(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnCosultar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tlbReservas = new javax.swing.JTable();
        lblIDReserva = new javax.swing.JLabel();
        lblFkPasajero = new javax.swing.JLabel();
        lblFkVuelo = new javax.swing.JLabel();
        lblFechaReserva = new javax.swing.JLabel();
        lblPrecioFinal = new javax.swing.JLabel();
        txtIDReserva = new javax.swing.JTextField();
        txtFkPasajero = new javax.swing.JTextField();
        txtNomPasajero = new javax.swing.JTextField();
        txtFKVuelo = new javax.swing.JTextField();
        txtPrecioFinal = new javax.swing.JTextField();
        jdcFechaReserva = new com.toedter.calendar.JDateChooser();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscar.setFont(new java.awt.Font("Racer", 0, 14)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 110, 27));

        btnNuevo.setFont(new java.awt.Font("Racer", 0, 14)); // NOI18N
        btnNuevo.setText("NUEVO");
        btnNuevo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 110, 27));

        btnCosultar.setFont(new java.awt.Font("Racer", 0, 14)); // NOI18N
        btnCosultar.setText("CONSULTAR");
        btnCosultar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCosultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCosultarActionPerformed(evt);
            }
        });
        add(btnCosultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 110, 27));

        btnGuardar.setFont(new java.awt.Font("Racer", 0, 14)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 110, 27));

        btnBorrar.setFont(new java.awt.Font("Racer", 0, 14)); // NOI18N
        btnBorrar.setText("BORRAR");
        btnBorrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 110, 27));

        tlbReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tlbReservas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 610, 140));

        lblIDReserva.setFont(new java.awt.Font("Racer", 0, 18)); // NOI18N
        lblIDReserva.setText("IDENTIFICADOR RESERVA");
        add(lblIDReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, 30));

        lblFkPasajero.setFont(new java.awt.Font("Racer", 0, 18)); // NOI18N
        lblFkPasajero.setText("IDENTIFICADOR PASAJERO");
        add(lblFkPasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, 30));

        lblFkVuelo.setFont(new java.awt.Font("Racer", 0, 18)); // NOI18N
        lblFkVuelo.setText("IDENTIFICADOR VUELO");
        add(lblFkVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, 30));

        lblFechaReserva.setFont(new java.awt.Font("Racer", 0, 18)); // NOI18N
        lblFechaReserva.setText("FECHA RESERVA");
        add(lblFechaReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, 30));

        lblPrecioFinal.setFont(new java.awt.Font("Racer", 0, 18)); // NOI18N
        lblPrecioFinal.setText("PRECIO FINAL");
        add(lblPrecioFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, 30));

        txtIDReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDReservaActionPerformed(evt);
            }
        });
        add(txtIDReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 110, 30));

        txtFkPasajero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFkPasajeroFocusLost(evt);
            }
        });
        add(txtFkPasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 110, 30));

        txtNomPasajero.setEditable(false);
        add(txtNomPasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 110, 30));
        add(txtFKVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 110, 30));
        add(txtPrecioFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 110, 30));
        add(jdcFechaReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 130, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        String ID = "";
        if (  ID.equals(txtIDReserva.getText() ) ){
            JOptionPane.showMessageDialog(null,
                "Debe digitar algo en el campo de Identificador",
                "Mensaje Importante",
                JOptionPane.ERROR_MESSAGE);
        } else{
            try{
                Reservas miReserva = Conexion.obtenerReserva(txtIDReserva.getText() );
                txtFkPasajero.setText(String.valueOf(miReserva.getPasajeroID()));
                txtFKVuelo.setText(String.valueOf(miReserva.getVueloID()));
                jdcFechaReserva.setDate(new java.util.Date(miReserva.getFechaReserva().getTime()));
                txtPrecioFinal.setText(miReserva.getPrecioFinal());
            }catch (SQLException ex){
                Logger.getLogger(JPLPasajeros.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        try {
            int siguiente = Conexion.siguienteReserva();
            txtIDReserva.setText(String.valueOf(siguiente) );
        } catch (SQLException ex) {
            Logger.getLogger(JPLReservas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnCosultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCosultarActionPerformed
        ResultSet resultad;
        try {
            resultad = Conexion.listarReserva();
            tlbReservas.setModel(DbUtils.resultSetToTableModel(resultad));
        } catch (SQLException ex) {
            Logger.getLogger(JPLReservas.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_btnCosultarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        //-- Guardar asume guardar nuevo y modificar

        //-- Creamos una copia del objeto y le llenamos los datos con el formulario
        Reservas miReserva = new Reservas();
        miReserva.setReservaID(Integer.parseInt(txtIDReserva.getText()));
        miReserva.setPasajeroID(Integer.parseInt(txtFkPasajero.getText()));
        miReserva.setVueloID(Integer.parseInt(txtFKVuelo.getText()));
        miReserva.setFechaReserva(new java.sql.Date(jdcFechaReserva.getDate().getTime()));
        miReserva.setPrecioFinal(txtPrecioFinal.getText());
        int indice = 0;

        try {
            Reservas Consultada = Conexion.obtenerReserva(txtIDReserva.getText() );
            if (Consultada != null){
                indice = Consultada.getReservaID();
            }
            else {
                indice = 0;
            }
        } catch (SQLException ex) {
            indice = 0;
        }

        //---Insertar o Modificar en la tabla
        if (indice == 0){
            try {

                if (Conexion.insertReserva(miReserva) != 0) {
                    JOptionPane.showMessageDialog(null, "Reserva Guardada" );
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.toString() );
            }
        }else{
            try {
                if (Conexion.updateReserva(miReserva) != 0) {
                    JOptionPane.showMessageDialog(null, "Reserva Modificada" );
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.toString() );
            }

        }
        btnCosultar.doClick();
        limpiar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        String ID = "";
        if (  ID.equals(txtIDReserva.getText() ) ){
            JOptionPane.showMessageDialog(null,
                "Debe digitar algo en el campo de Identificador",
                "Mensaje Importante",
                JOptionPane.ERROR_MESSAGE);
        } else{
            try{
                if (Conexion.borrarReserva(Integer.parseInt(txtIDReserva.getText())) != 0) {
                    JOptionPane.showMessageDialog(null, "Reserva Borrada" );
                }
            }catch (SQLException ex) {
                Logger.getLogger(JPLReservas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        btnCosultar.doClick();
        limpiar();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void txtIDReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDReservaActionPerformed

    }//GEN-LAST:event_txtIDReservaActionPerformed

    private void txtFkPasajeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFkPasajeroFocusLost
                 int ID = Integer.parseInt(txtFkPasajero.getText());       
        try{
            txtNomPasajero.setText(Conexion.nombrePasajero(ID));
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_txtFkPasajeroFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCosultar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcFechaReserva;
    private javax.swing.JLabel lblFechaReserva;
    private javax.swing.JLabel lblFkPasajero;
    private javax.swing.JLabel lblFkVuelo;
    private javax.swing.JLabel lblIDReserva;
    private javax.swing.JLabel lblPrecioFinal;
    private javax.swing.JTable tlbReservas;
    private javax.swing.JTextField txtFKVuelo;
    private javax.swing.JTextField txtFkPasajero;
    private javax.swing.JTextField txtIDReserva;
    private javax.swing.JTextField txtNomPasajero;
    private javax.swing.JTextField txtPrecioFinal;
    // End of variables declaration//GEN-END:variables
}
