/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import Datos.Conexion;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import  java.sql.ResultSet;
import net.proteanit.sql.DbUtils;
import Datos.Aeropuertos;
import Datos.Vuelos;
/**
 *
 * @author irvin
 */
public class JPLVuelos extends javax.swing.JPanel {

    /**
     * Creates new form JPLVuelos
     */
    public JPLVuelos() {
        initComponents();
    }
            private void limpiar()
    {
        txtIDVuelo.setText("");
        txtNumeroVuelo.setText("");
        txtNomAeroOrigen.setText("");
        txtNomAeroDes.setText("");
        jdcFechaSalida.setDate(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnCosultar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tlbVuelos = new javax.swing.JTable();
        lblIDVuelo = new javax.swing.JLabel();
        lblNumeroVuelo = new javax.swing.JLabel();
        lblFKAeroOri = new javax.swing.JLabel();
        lblFkAeroDes = new javax.swing.JLabel();
        lblFechaSalida = new javax.swing.JLabel();
        txtIDVuelo = new javax.swing.JTextField();
        txtNumeroVuelo = new javax.swing.JTextField();
        txtFkAeroOrigen = new javax.swing.JTextField();
        txtNomAeroOrigen = new javax.swing.JTextField();
        txtFkAeroDes = new javax.swing.JTextField();
        txtNomAeroDes = new javax.swing.JTextField();
        jdcFechaSalida = new com.toedter.calendar.JDateChooser();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscar.setFont(new java.awt.Font("Racer", 0, 14)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 110, 27));

        btnNuevo.setFont(new java.awt.Font("Racer", 0, 14)); // NOI18N
        btnNuevo.setText("NUEVO");
        btnNuevo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 110, 27));

        btnCosultar.setFont(new java.awt.Font("Racer", 0, 14)); // NOI18N
        btnCosultar.setText("CONSULTAR");
        btnCosultar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCosultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCosultarActionPerformed(evt);
            }
        });
        add(btnCosultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 110, 27));

        btnGuardar.setFont(new java.awt.Font("Racer", 0, 14)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 110, 27));

        btnBorrar.setFont(new java.awt.Font("Racer", 0, 14)); // NOI18N
        btnBorrar.setText("BORRAR");
        btnBorrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 110, 27));

        tlbVuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tlbVuelos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 610, 140));

        lblIDVuelo.setFont(new java.awt.Font("Racer", 0, 18)); // NOI18N
        lblIDVuelo.setText("IDENTIFICADOR VUELO");
        add(lblIDVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, 30));

        lblNumeroVuelo.setFont(new java.awt.Font("Racer", 0, 18)); // NOI18N
        lblNumeroVuelo.setText("NUMERO DE VUELO");
        add(lblNumeroVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, 30));

        lblFKAeroOri.setFont(new java.awt.Font("Racer", 0, 18)); // NOI18N
        lblFKAeroOri.setText("IDENTIFICADOR AEROPUERTO ORIGEN");
        add(lblFKAeroOri, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 30));

        lblFkAeroDes.setFont(new java.awt.Font("Racer", 0, 18)); // NOI18N
        lblFkAeroDes.setText("IDENTIFICADOR AEROPUERTO DESTINO");
        add(lblFkAeroDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, 30));

        lblFechaSalida.setFont(new java.awt.Font("Racer", 0, 18)); // NOI18N
        lblFechaSalida.setText("FECHA DE SALIDA");
        add(lblFechaSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 338, -1, 30));
        add(txtIDVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 100, -1));
        add(txtNumeroVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 100, -1));

        txtFkAeroOrigen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFkAeroOrigenFocusLost(evt);
            }
        });
        add(txtFkAeroOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 100, -1));

        txtNomAeroOrigen.setEditable(false);
        add(txtNomAeroOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 100, -1));

        txtFkAeroDes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFkAeroDesFocusLost(evt);
            }
        });
        add(txtFkAeroDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 100, -1));

        txtNomAeroDes.setEditable(false);
        add(txtNomAeroDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 100, -1));
        add(jdcFechaSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 100, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        String ID = "";
        if (  ID.equals(txtIDVuelo.getText() ) ){
            JOptionPane.showMessageDialog(null,
                "Debe digitar algo en el campo de Identificador",
                "Mensaje Importante",
                JOptionPane.ERROR_MESSAGE);
        } else{
            try{
                Vuelos miVuelo = Conexion.obtenerVuelo(txtIDVuelo.getText() );
                txtNumeroVuelo.setText(miVuelo.getNumeroVuelo());
                txtNomAeroOrigen.setText(String.valueOf(miVuelo.getAeropuertoOrigenID()));
                txtNomAeroDes.setText(String.valueOf(miVuelo.getAeropuertoDestinoID()));
                jdcFechaSalida.setDate(new java.util.Date(miVuelo.getFechaSalida().getTime()));
            }catch (SQLException ex){
                Logger.getLogger(JPLAeropuertos.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        try {
            int siguiente = Conexion.siguienteVuelo();
            txtIDVuelo.setText(String.valueOf(siguiente) );
        } catch (SQLException ex) {
            Logger.getLogger(JPLVuelos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnCosultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCosultarActionPerformed
        ResultSet resultad;
        try {
            resultad = Conexion.listarVuelo();
            tlbVuelos.setModel(DbUtils.resultSetToTableModel(resultad));
        } catch (SQLException ex) {
            Logger.getLogger(JPLVuelos.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_btnCosultarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        //-- Guardar asume guardar nuevo y modificar

        //-- Creamos una copia del objeto y le llenamos los datos con el formulario
        Vuelos miVuelo = new Vuelos();
        miVuelo.setVueloID(Integer.parseInt(txtIDVuelo.getText()));
        miVuelo.setNumeroVuelo(txtNumeroVuelo.getText());
        miVuelo.setAeropuertoOrigenID(Integer.parseInt(txtFkAeroOrigen.getText()));
        miVuelo.setAeropuertoDestinoID(Integer.parseInt(txtFkAeroDes.getText()));
        miVuelo.setFechaSalida(new java.sql.Date(jdcFechaSalida.getDate().getTime()));
        int indice = 0;

        try {
            Vuelos Consultada = Conexion.obtenerVuelo(txtIDVuelo.getText() );
            if (Consultada != null){
                indice = Consultada.getVueloID();
            }
            else {
                indice = 0;
            }
        } catch (SQLException ex) {
            indice = 0;
        }

        //---Insertar o Modificar en la tabla
        if (indice == 0){
            try {

                if (Conexion.insetVuelo(miVuelo) != 0) {
                    JOptionPane.showMessageDialog(null, "Vuelo Guardado" );
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.toString() );
            }
        }else{
            try {
                if (Conexion.updateVuelo(miVuelo) != 0) {
                    JOptionPane.showMessageDialog(null, "Vuelo Modificado" );
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.toString() );
            }

        }
        btnCosultar.doClick();
        limpiar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        String ID = "";
        if (  ID.equals(txtIDVuelo.getText() ) ){
            JOptionPane.showMessageDialog(null,
                "Debe digitar algo en el campo de Identificador",
                "Mensaje Importante",
                JOptionPane.ERROR_MESSAGE);
        } else{
            try{
                if (Conexion.borrarVuelo(Integer.parseInt(txtIDVuelo.getText())) != 0) {
                    JOptionPane.showMessageDialog(null, "Vuelo Borrado" );
                }
            }catch (SQLException ex) {
                Logger.getLogger(JPLVuelos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        btnCosultar.doClick();
        limpiar();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void txtFkAeroOrigenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFkAeroOrigenFocusLost
                          int ID = Integer.parseInt(txtFkAeroOrigen.getText());       
        try{
            txtNomAeroOrigen.setText(Conexion.nombreAeropuerto(ID));
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_txtFkAeroOrigenFocusLost

    private void txtFkAeroDesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFkAeroDesFocusLost
                          int ID = Integer.parseInt(txtFkAeroDes.getText());       
        try{
            txtNomAeroDes.setText(Conexion.nombreAeropuerto(ID));
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_txtFkAeroDesFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCosultar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcFechaSalida;
    private javax.swing.JLabel lblFKAeroOri;
    private javax.swing.JLabel lblFechaSalida;
    private javax.swing.JLabel lblFkAeroDes;
    private javax.swing.JLabel lblIDVuelo;
    private javax.swing.JLabel lblNumeroVuelo;
    private javax.swing.JTable tlbVuelos;
    private javax.swing.JTextField txtFkAeroDes;
    private javax.swing.JTextField txtFkAeroOrigen;
    private javax.swing.JTextField txtIDVuelo;
    private javax.swing.JTextField txtNomAeroDes;
    private javax.swing.JTextField txtNomAeroOrigen;
    private javax.swing.JTextField txtNumeroVuelo;
    // End of variables declaration//GEN-END:variables
}
